name: Create and publish a Docker image

on:
  push:
    branches: ["main"]

env:
  REGISTRY: registry.test.com
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        # Checkout the current branch, not the default branch
        with:
          ref: ${{ github.ref }}

      - name: Install OVH AI cli
        run: |
          curl https://cli.gra.training.ai.cloud.ovh.net/install.sh | bash

      - name: Login to OVH AI
        run: |
          $HOME/bin/ovhai login --username ${{ secrets.OVHAI_USERNAME }} --password ${{ secrets.OVHAI_PASSWORD }}

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.OVH_REGISTRY_USERNAME }}
          password: ${{ secrets.OVH_REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: '${{ env.REGISTRY }}/docker-demo/${{ github.ref }}:latest'
